name: "3. Build latest tags images"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["2. Build dev-next images"]
    branches: [main]
    types:
      - completed

jobs:
  Building:
    runs-on: ubuntu-latest
    name: "Build image"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ $VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Read version from README.md
        run: |
          [ -e README.md ] && VERSION=$(awk '/^ - ### \*\*latest\*\*:/{print $NF}' README.md)
          echo "VERSION: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        if: ${{ env.VERSION != '' }}
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to Docker hub
        if: ${{ env.VERSION != '' }}
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          file: main/Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          tags: ${{ env.DOCKERHUB_REPOSITORY }} 

      - name: Upload to repository
        if: ${{ env.VERSION != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Build ${{ env.VERSION }} by Github Actions, ${{ env.DATE }}
